### ISSUE TITLE
Add API Documentation (GoDoc) to github pages

### ISSUE THREAD

**Issue by davidiw** [DeDiS/crypto#14]
It would be great if in addition to the recent CI work, we could also have the GoDoc published and automatically updated at this URL http://dedis.github.io/crypto every time a new merge into master occurs. Could someone look into this?

**Comment by bford** [comment]
Perhaps looking into - however, I'm not sure how critical this is, since the GoDoc-generated documentation is already published and readily available at:

http://godoc.org/github.com/DeDiS/crypto

...as the README at the top of the crypto library already points out.  Is there some reason you think it's important for the documentation to have a github.com URL rather than a godoc.org URL?

**Comment by dyv** [comment]
I have a script at github.com/dyv/dedis-docs that polls GitHub pulls down changes and runs a godoc server. It has the advantage of also doing pointer and type analysis of the code so you can see the call graphs, what interfaces a struct implements, what structs implement an interface, and other analysis as described in the godoc documentation. As far as official documentation goes most projects I have seen use a readme and link to the official godoc site. The only advantage of this tool is it provides helpful analysis the official godoc does not.

**Comment by davidiw** [comment]
No Bryan, I had a "I didn't RTFM" moment :).

And Dylan, nice work, that answered the second part of my question
(automated building of the docs)

I guess one other thing that might be nice is that if there is a possible
delay in updating godocs, that we also post the commit that the build was
based upon, but that is really low priority.

I'll close this issue.
