### ISSUE TITLE
Equal Troubles

### ISSUE THREAD

**Issue by WEB3-GForce** [DeDiS/crypto#21]
@jackowitzd2
@bford 

I am running into issues with testing equality for extPoint. When I run tests, I get a nil pointer error. As diagnostics, I have written the following code in my testing procedures:

var group abstract.Group = new(edwards.ExtendedCurve).Init(
	edwards.Param25519(), false)
var k int = 10
var n int = 20
var secret = group.Secret()
var point  = group.Point()
...
func TestGroup(t *testing.T) {
	group.Point().Equal(group.Point())
}

When I then run the code, I get the following error

--- FAIL: TestGroup (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x50bfcc]

goroutine 21 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
math/big.(*Int).Mod(0xc208048030, 0xc208048030, 0x0, 0xc208048030)
	/usr/local/go/src/math/big/int.go:251 +0x22c
github.com/dedis/crypto/nist.(*Int).Mul(0xc208048030, 0x7f7755b31e68, 0xc208062160, 0x7f7755b31e68, 0xc208062260, 0x0, 0x0)
	/home/william/Desktop/CPSC490/src/src/github.com/dedis/crypto/nist/int.go:219 +0x122
github.com/dedis/crypto/edwards.(*extPoint).Equal(0xc208062160, 0x7f7755b31dc8, 0xc208062210, 0x54c61991)
	/home/william/Desktop/CPSC490/src/src/github.com/dedis/crypto/edwards/ext.go:81 +0x121
github.com/dedis/crypto/poly.TestGroup(0xc20808a090)
	/home/william/Desktop/CPSC490/src/src/github.com/dedis/crypto/poly/sharing_test.go:279 +0x90
testing.tRunner(0xc20808a090, 0x699de0)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x608798, 0x699c60, 0x15, 0x15, 0xd1735f78be5cda01)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20805dbd0, 0x6a2f20)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/dedis/crypto/poly/_test/_testmain.go:92 +0x1d5
exit status 2
FAIL	github.com/dedis/crypto/poly	0.095s

Here is some more code on this:

edwards/ext.go

func (P1 *extPoint) Equal(CP2 abstract.Point) bool {
	P2 := CP2.(*extPoint)
	var t1, t2 nist.Int
	xeq := t1.Mul(&P1.X, &P2.Z).Equal(t2.Mul(&P2.X, &P1.Z)) <-------- 
	yeq := t1.Mul(&P1.Y, &P2.Z).Equal(t2.Mul(&P2.Y, &P1.Z)) 
	return xeq && yeq
}

nist/Int.go:

func (i *Int) Mul(a, b abstract.Secret) abstract.Secret {
	ai := a.(*Int)
	bi := b.(*Int)
	i.M = ai.M
	i.V.Mul(&ai.V, &bi.V).Mod(&i.V, i.M)  <----
	return i
}

It seems to be an initialization issue. As one last thing, I researched more on how the point is made:

edwards/ext.go

// Create a new Point on this curve.
func (c *ExtendedCurve) Point() abstract.Point {
	P := new(extPoint)
	P.c = c
	//P.Set(&c.null)
	return P
}

type extPoint struct {
	X, Y, Z, T nist.Int
	c          *ExtendedCurve
}

Should the Point function do any additional initialization (or does it expect me to do so)?

**Comment by bford** [comment]
Sorry I wasn't able to get back to looking at this until now.

The intention of both the Point and Secret interfaces is that you are supposed to set objects of those classes explicitly to *something* before you try to use them (e.g., in Equal or any other method that reads them).  For example, if you want to compare a point P against the neutral element, then you might do P.Equal(suite.Point().Null()), not just P.Equal(suite.Point()).  If you want to compare P against the standard base point, you might do P.Equal(suite.Point().Base()).  I just committed a change to the documentation for abstract.Group to clarify this requirement; sorry that was left unclear.

It's of course perfectly debatable whether the Point/Secret interfaces *should* require explicit initialization before use: for example, Go's big.Int does not require initialization before use, such that any uninitialized big.Int defaults to zero.  That's convenient, and probably makes sense for general-purpose big.Int calculations.  However, since Secret and Point objects are specifically intended for security-critical usage scenarios, in which buggy code that forgets to initialize a Secret or Point to the non-zero value it's supposed to have might very easily "fail open" and look like it's behaving correctly while in fact being completely insecure, it seemed to me that avoiding that security risk of actually having a Secret or Point default to a "null" value seems worth the slight convenience cost of requiring every Secret or Point to be explicitly initialized before use.

Make sense?
B

**Comment by WEB3-GForce** [comment]
Thanks, I thought group.Point() and group.Secret() returned initialized objects. I should be able to finish up the testing code now.

As a side note, for the different cryptographic schemes that we have, are there any that will generate a fresh, initialized secret (private key) and a point (public key) from that secret?

**Comment by bford** [comment]
> On Jan 28, 2015, at 3:31 PM, William Bailey <notifications@github.com> wrote:
> 
> Thanks, I thought group.Point() and group.Secret() returned initialized objects. I should be able to finish up the testing code now.
> 
> As a side note, for the different cryptographic schemes that we have, are there any that will generate a fresh, initialized secret (private key) and a point (public key) from that secret?
> 
Use Secret.Pick() to generate the fresh private key and Point.Mul() to produce its public key.  Just grep through the crypto library source code and existing test cases and you’ll find a lot of examples where that is done.

B

**Comment by WEB3-GForce** [comment]
Thanks!
