### ISSUE TITLE
stream.Cipher Partial hashing on key material seems inconsistent

### ISSUE THREAD

**Issue by davidiw** [DeDiS/crypto#32]
See https://github.com/DeDiS/crypto/blob/69145062a6b2137a89d34a8db803234481c31014/cipher/stream.go#L82

I think that hash should process all the contents of key and none if key is nil. I don't see there being any security benefits to the current approach, only performance disadvantages.

**Comment by bford** [comment]
Ah, yes - in fact I think that's how I had intended it to work, but apparently forgot to wrap key-absorbing lines (81-87) with an "if key != nil".  Thanks for noticing that.  

(However, I think the behavior should be the same as it is currently if key != nil but is shorter than n, for consistency with the way the other slice parameters work.)

**Comment by davidiw** [comment]
Hmm... I have a few scattered thoughts on this:
- Panic if len(src) != len(dst) != len(key)
Why would they ever be different lengths? This would seem like a programmer bug.

- Panic if dst < src
I could imagine a user rounding up his dst to the next block size, but I cannot imagine why it would ever be smaller than src.

- What is the benefit of adding 0 bytes into a hash? Does the sponge do this?

**Comment by bford** [comment]
Bullet #1: It might be reasonable to require src, len, and key to be of the same lengths - but only the ones that are non-nil. It's important for various use-cases that all the parameters be optional. 

I had considered making a same-length requirement for non-nil parameters, but this slightly more flexible behavior turned out to be almost as simple to code in the end, and the potentially interesting use-case it allows is for (say) padding a shorter plaintext with implicit zeros during encryption to produce a fixed-length (padded) ciphertext, and stripping that padding on the decryption side, without having to do an extra buffer-copy on either the encryption or decryption sides.  Not an earthshakingly important use case, at least so far, but still it seemed to provide at least one motivation for why the "most general" behavior could actually be useful.

Bullet #2: see above - the decryption case for unpadding a padded ciphertext without having to decrypt to a separate buffer and then copy the subset that's actually needed.  Not that I'm actually using this (yet) in any code, but it seemed conceivably useful anyway, and made the semantics of all parameters nicely symmetrical.

Bullet #3: The sponge does this.  The benefit is that the result of the hash - and hence the Cipher's state for whatever "next" message it processes - will depend on the exact length of the message absorbed this time around, even if some or all of the bits of that message is zero.  In the case of the padded message, for example, it's important that the zero-byte padding be accounted for in any MAC of the message; if it isn't, then there are well-known attacks in which an attacker can fiddle with the last bytes in the ciphertext before the MAC to see if they break decryption, thereby learning how much of the message is "real" and how much is padding, and from there have strengthened traffic analysis attacks or other side-channel attacks.

Basically, the motivation behind the design is that, semantically, the Cipher always processes n=max(len(src),len(dst),len(key)) bytes for a given "message" - hence the "message length" is semantically always n - but allowing src, dst, or key to be shorter than n (but nonzero) is just an API convenience that doesn't change the basic semantics (in particular message length) as it affects the behavior of the Cipher.

One more point: this "streamCipher" module is there mainly as both a proof-of-concept and an experimentation vehicle for demonstrating and testing how the general "message cipher" abstraction may be built out of conventional block/stream ciphers and hashes.  This module (and in general this method of constructing message ciphers) is not intended for actual "recommended use" in any realistic setting I can think of, simply because it's probably always going to be substantially less efficient than using a state-of-the-art sponge function, of which at least one (SHA3/SHAKE) is already an accepted standard.  In particular, the block/stream+hash construction inherently requires processing every byte of a message through both the cipher *and* the hash function in authenticated-encryption use-cases, whereas a sponge construction requires only one execution of the underlying sponge function per capacity-bytes of message or ciphertext regardless of whether we're doing just encryption, just authentication/hashing, or both together.  

So yes, the sponge cipher version does add 0 bytes into a hash, but it doesn't cost anything to do that in that case.  And I don't care all that much about the efficiency of the streamCipher construction because I don't expect that construction needs to or should ever really go into common use anyway.

**Comment by bford** [comment]
@davidiw anything you think we should do or further discuss on this?

**Comment by davidiw** [comment]
Push a commit for fixing the key != nil and will consider this closed unless there are evaluations that recommend revisiting it (namely that sponge is slower than encrypt + hash separately).
