### ISSUE TITLE
Nil Cipher Options

### ISSUE THREAD

**Issue by WEB3-GForce** [DeDiS/crypto#41]
@bford 

For abstract.Group:

     Cipher(key []byte, options ...interface{}) Cipher

When I try to create a cipher with a suite:

    cipher := p.shareSuite.Cipher(diffieBase.MarshalBinary())

I get the following error:

     2015/02/27 18:09:55 Unsupported option <nil>
         panic: Unsupported option <nil>

When I checked "cipher/sponge", I saw the issue:

    func (sc *spongeCipher) parseOptions(options []interface{}) bool {
        more := false
        for _, opt := range options {
             switch v := opt.(type) {
                 case Padding:
                     sc.pad = byte(v)
                default:
                     log.Panicf("Unsupported option %v", opt)
            }
         }
         return more
     }

It doesn't have a case for handling a nil options. However, it seems as though the options parameter is optional since I was able to call Cipher by only specifying the bytes field. I did the following fix and everything worked:

    func (sc *spongeCipher) parseOptions(options []interface{}) bool {
        more := false
        for _, opt := range options {
             switch v := opt.(type) {
                 case Padding:
                     sc.pad = byte(v)
                 case nil:
                     continue
                default:
                     log.Panicf("Unsupported option %v", opt)
            }
         }
         return more
     }

Is this functionality desirable?

**Comment by bford** [comment]
No, we don't want to ignore a 'nil' option silently.

However, I think this is probably a result of a missing '...' in some call somewhere in this Cipher constructor call-chain, resulting in a nil *option-list* being passed as an *option* (rather than as an option-list).  Let me look at the code.

**Comment by bford** [comment]
I really need to know what your 'p.shareSuite' is defined as - i.e., which cipher suite you're using - in order to be able to trace this efficiently.

In general, it would be most helpful if whenever you bring up an issue you include a reference to a specific branch in your repo where the code encountering the problem may be found.

**Comment by WEB3-GForce** [comment]
The branch is pull request #40 

The code snippet above was from diffieHellmanEncrypt.

The suite that I am using is 

    var keySuite = nist.NewAES128SHA256P256()

**Comment by bford** [comment]
Aha.  The problem is that point.MarshalBinary() returns *two* values: a []byte slice, and an error.  You're feeding MarshalBinary()'s two-value return directly to the Cipher() constructor.  The Go compiler is allowing that because the first return value is indeed a []byte-slice as required, and the second return value can be treated as a singleton-size list of interface{}, i.e., something that "can be" interpreted as a list of options (though it obviously makes no semantic sense to do so).  Since MarshalBinary() is succeeding, the returned 'error' pointer is nil, hence the complaint about an unknown option nil.

So you need to do something like "buf, err := diffieBase.MarshalBinary()" first, check that the error return is nil (it may be OK just to panic here if not, if the diffieBase parameter is always supposed to contain a valid and marshal able point), then pass 'buf' to Cipher().

**Comment by WEB3-GForce** [comment]
Thanks, that did the trick.
