### ISSUE TITLE
Code does not adhere to gofmt standard

### ISSUE THREAD

**Issue by dyv** [DeDiS/crypto#5]
Code does not adhere to the gofmt standards. The Go community expects that all good go code is formatted according to this standard (http://blog.golang.org/go-fmt-your-code, http://golang.org/doc/effective_go.html#formatting, https://github.com/golang/go/wiki/CodeReviewComments#gofmt). This is a necessary step for being taken seriously by the community at large.

It makes life much easier, as you can hook gofmt to run on save for most editors and it will deal with all formatting (http://blog.golang.org/go-fmt-your-code). There is an extension called goimports that you can run instead that analyzes your code, formats it, and handles imports (dropping them or adding them as needed). This will make dependency management easier as there will not be the "unused import" error and files won't have stray, commented out imports.

All these commands run very quickly, almost unnoticably quickly.

**Comment by bford** [comment]
It occurs to me that what we probably want, both to address 'gofmt enforcement' for new commits and for broader 'make sure it still builds and tests after this next change', is a suitable automated CI (Contiunuous Integration) setup.  I see that github has presumably mature and commonly-used support for this, e.g., see: https://developer.github.com/guides/building-a-ci-server/

We'd presumably need to set up a CI server somewhere (e.g., on korz, our main internal server) (unless there's a service already out there willing to volunteer the CPU cycles to do actual go build and gofmt tests for us, which there might not be since that's probably more CPU-intensive and less monetizable than the services github provides).  It looks like "Jenkins" is one of the commonly-used CI server platforms, although I so far no nothing about it in particular.  It looks like someone has also written a "Jenkins-like" CI server in Go: https://github.com/jakecoffman/gorunner

Dylan (or anyone), want to see if it's quick-and-easy to hack together a basic CI server setup that basically (a) runs 'gofmt -l' on all files touched by a pull request, and (b) runs 'go test -v ./...' on the whole tree in a pull request?  Probably others out there have done exactly this already; it might just amount to a bit of digging.

**Comment by dyv** [comment]
I will look into this. Is all of the code publicly hosted on Github or will there be pieces of it that are not hosted (for security reasons etc.)? There are CI servers that will help open source projects for free. They only cost money when they are private repositories.

**Comment by bford** [comment]
My intent is that ALL of the code (that would need to be touched by CI servers) will be public and therefore hostable on github.  As mentioned in the E-mail I just on the dissent list, some of the relevant internal documentation may not be (partly for security/privacy reasons) - but that shouldn't affect what CI servers need to do.

**Comment by davidiw** [comment]
This CI server stuff seems neat, but hopefully everyone is checking format
and eliminating warnings before asking for a commit. How does github
integrate the CI? Push -> CI Server, then I guess fail means the pusher
gets notification, on pass it notifies those appropriately subscribed to
the repo?

**Comment by bford** [comment]
On Jan 8, 2015, at 1:11 PM, David Isaac Wolinsy <notifications@github.com> wrote:
> This CI server stuff seems neat, but hopefully everyone is checking format 
> and eliminating warnings before asking for a commit. How does github 
> integrate the CI? Push -> CI Server, then I guess fail means the pusher 
> gets notification, on pass it notifies those appropriately subscribed to 
> the repo? 

It might do that, but I would also be happy with the less-Fascist behavior of simply attaching a warning to the pull request (e.g., "failed gofmt test" or "failed build test"), which it looks like github is set up to do.  We can always not accept pull requests until the warnings go away. :)

B

**Comment by bford** [comment]
CI server stuff including gofmt checker seems to be working now, thanks Dylan.  (I had to edit .travis.yml further to pull in import dependencies that only tests require, which weren't getting sucked in.)
